[[headers]]
    for = "/*"
    [headers.values]
    X-Frame-Options = 'DENY'
    X-Content-Type-Options = 'nosniff'
    X-XSS-Protection = '1; mode=block'
    Referrer-Policy = 'no-referrer'
    Permissions-Policy = 'microphone=(), camera=(), geolocation=()'
    Content-Security-Policy = '''
        default-src 'none'; 
        style-src 'self'; 
        style-src-elem 'self'; 
        font-src 'self'; 
        form-action 'none'; 
        script-src 'self'; 
        connect-src 'self'; 
        img-src 'self' data:; 
        media-src 'self'; 
        base-uri 'none'; 
        manifest-src 'self'; 
        child-src 'none'; 
        frame-ancestors 'none'; 
        object-src 'self';
        navigate-to 'self' https://github.com https://linkedin.com; 
        sandbox allow-same-origin allow-scripts allow-popups allow-downloads allow-popups-to-escape-sandbox; 
        upgrade-insecure-requests;'''